name: Copier Source Template Update

on:
  schedule:
    - cron: "0 2 * * 1" # Every Monday at 2am
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Copier & Inject Dependencies
        run: |
          pipx install copier
          pipx inject copier -r .devcontainer/library/requirements.txt
      - name: Run Copier Update
        run: copier update --skip-answered --trust
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "refactor: apply template"
          branch: copier-template-update
          delete-branch: true
          branch-suffix: timestamp
          title: "refactor: apply template"
          body: |
            Copier has applied from the template repository.

            Check out the branch for the PR and edit as needed.