name: Tests

on:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Example Tests
        run: |
          FILE=README.md
          if [ -f "$FILE" ]; then
            echo "$FILE exists."
            echo "Also you should probably put one or more real checks relevant to your project here."
          else
            echo "$FILE missing!"
            exit 1
          fi
